import React, { useState } from 'react'
import toast, { Toaster } from 'react-hot-toast'
import * as urlService from '../services/urlService'
import { useUrl } from './UrlContext'
import { nanoid } from 'nanoid'

const CreateUrls = () => {
  const [url, setUrl] = useState({
    url: '',
    surl: '',
  })
  const { urls, setUrls } = useUrl()
  const handleChange = (e: Event | any) => {
    e = e || window.event
    e.preventDefault()
    const { name, value } = e.target
    setUrl({ ...url, [name]: value })
    return handleChange
  }

  const handleSubmit = async (e: Event | any) => {
    e = e || window.event
    e.preventDefault()
    const data = {
      url: url.url,
      surl: url.surl,
    }
    if (data.surl === '') {
      data.surl = nanoid(10)
    }
    const sUrl = urlService.createUrl(data)
    const newUrl = {
      original_url: data.url,
      short_url: data.surl,
    }
    const newUrls = [newUrl, ...urls]
    try {
      await sUrl
      setUrls(newUrls)
      toast.promise(sUrl, {
        loading: 'Loading',
        success: 'Url shortened successfully',
        error: 'Unable to shorten url',
      })

      setUrl({
        url: '',
        surl: '',
      })
    } catch (ex: any) {
      toast.error(ex.response.data)
    }
  }

  return (
    <section className=" mt-2 flex w-full flex-row items-center  px-2 py-2 md:px-24 xl:px-20">
      <form
        onSubmit={handleSubmit}
        className="flex w-full  flex-col items-center gap-6 rounded-xl bg-zinc-100 p-6 shadow-[0_35px_60px_-15px]  shadow-[#FFBA49] dark:bg-zinc-900 dark:shadow-[#EF5B5B]  lg:mx-16 lg:h-20 lg:flex-row lg:justify-between lg:gap-4 lg:px-4"
      >
        <input
          className="w-full appearance-none rounded-lg bg-gray-400 bg-opacity-40 py-3 px-4 leading-tight text-gray-900  outline-none transition-all duration-500 focus:bg-opacity-20 dark:bg-zinc-700  dark:bg-opacity-40 dark:text-gray-200 dark:focus:bg-opacity-100  "
          id="url"
          type="url"
          value={url.url}
          onChange={handleChange}
          title="Enter a valid URL"
          name="url"
          placeholder="URL"
        />
        <input
          className="w-full appearance-none rounded-lg  bg-gray-400 bg-opacity-40 py-3 px-4 leading-tight text-gray-900  outline-none transition-all duration-500 focus:bg-opacity-20 dark:bg-zinc-700  dark:bg-opacity-40 dark:text-gray-200 dark:focus:bg-opacity-100  "
          id="surl"
          value={url.surl}
          onChange={handleChange}
          type="text"
          title="Short url should be 3-50 characters and should contain letters and numbers only otherwise it will be generated automatically"
          pattern="[a-zA-Z0-9]{3,50}"
          name="surl"
          placeholder="Short URL (Autogenerated)"
        />
        <button className="flex items-center justify-center rounded-lg bg-gray-300 bg-opacity-20 px-5 py-2 text-2xl   backdrop-blur-2xl transition-all  duration-500 hover:bg-opacity-100 active:scale-75 dark:bg-zinc-700  dark:bg-opacity-20 dark:backdrop-blur-2xl dark:hover:bg-opacity-100">
          <p className="animate-gradient-x  bg-gradient-to-r text-[#FFBA49]  dark:text-[#EF5B5B]  ">
            Shorten
          </p>
        </button>
      </form>
      <Toaster position="bottom-right" reverseOrder={false} />
    </section>
  )
}

export default CreateUrls
